export const GET_ALL_ORDER_REQ="GET_ALL_ORDER_REQ"
export const GET_ALL_ORDER_SUCCESS="GET_ALL_ORDER_SUCCESS"
export const GET_ALL_ORDER_ERR="GET_ALL_ORDER_ERR"
export const UPDATE_STATUS="UPDATE_STATUS"