export const ADD_TO_CART_REQ="ADD_TO_CART_REQ"

export const ADD_TO_CART_SUCCESS="ADD_TO_CART_SUCCESS"

export const ADD_TO_CART_ERROR="ADD_TO_CART_ERROR"

export const QUANTITY_REQ="QUANTITY_REQ"
export const INC_QUANTITY="INC_QUANTITY"
export const DEC_QUANTITY="DEC_QUANTITY"
export const QUANTITY_ERR="QUANTITY_ERR"

export const GET_CART_ITEM_REQ="GET_CART_ITEM_REQ"

export const GET_CART_ITEM_SUCCESS="GET_CART_ITEM_SUCCESS"

export const GET_CART_ITEM_ERROR="GET_CART_ITEM_ERROR"

export const DELETE_CART_ITEM="DELETE_CART_ITEM"