export const GET_PRODUCT_REQ="GET_PRODUCT_REQ"

export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"

export const GET_PRODUCT_ERROR="GET_PRODUCT_ERROR"

export const DELETE_PRODUCT="DELETE_PRODUCT"


